<?xml version="1.0" encoding="UTF-8"?>
<!--声明内部DTD-->
<!DOCTYPE scores [
	<!ELEMENT scores (student+)>
	<!ELEMENT student (name,course,score)>
	<!ATTLIST student id CDATA #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT course (#PCDATA)>
	<!ELEMENT score (#PCDATA)>
]>

<scores>
	<student id="1">
		<name>张三</name>
		<course>Java</course>
		<score>98</score>
	</student>
	<student id="2">
		<name>李大夫</name>
		<course>数学</course>
		<score>46</score>
	</student>
	<student id="2">
		<name>王里</name>
		<course>C++</course>
		<score>46</score>
	</student>
</scores>
